### ISSUE TITLE
Support latest version of Flow (0.66)

### ISSUE THREAD

**Issue by ryami333** [amilajack/eslint-plugin-flowtype-errors#115]
Flow error messages got an overhaul in [Flow 0.66](https://github.com/facebook/flow/releases/tag/v0.66.0). Using this latest release with `eslint-plugin-flowtype-errors` produces linting errors that just look like this:

![screen shot 2018-02-20 at 9 39 27 am](https://user-images.githubusercontent.com/12481532/36396571-b94fb032-1623-11e8-83c8-002674abc61c.png)

**Comment by amilajack** [comment]
@jdmota wanna take a look at this?

**Comment by jdmota** [comment]
I'll take a look.

**Comment by jdmota** [comment]
I think the problem is here:

https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/e8ded7ff20ca80c621f7af96d2634f1dd840f546/src/collect.js#L254-L278

The references show up on the "extra" property. With this code, if the "extra" property is available, the actual message seems to be ignored.

I'm not sure what needs to be done. Did flow change the json output?

I think these code was made by @nwoltman. Can you help us? Thanks

**Comment by nwoltman** [comment]
I'm looking into it. Flow completely changed their output format.

**Comment by amilajack** [comment]
Published `3.5.0` which fixes this
